### ISSUE TITLE
DawnFortress missing

### ISSUE THREAD

**Issue by lethosor** [fricy/DFgraphics#11]
There is what appears to be a DawnFortress submodule in the root folder of this repo, but it is absent from .gitmodules and https://github.com/fricy/DawnFortress doesn't exist.

**Comment by fricy** [comment]
Yeah, I removed the repo because the author asked me to, and managed to mess it up in the process. I'm aware and will fix it. Eventually. Most likely this repo will go, and will be replaced by a smaller clean one with only the non-vanilla raws as the new launcher can work with only the reduced raw set.
Leaving this open as a reminder.

**Comment by lethosor** [comment]
`git rm DawnFortress` should do the trick.

**Comment by fricy** [comment]
git submodule deinit was the magic world
